### ISSUE TITLE
cannot import name 'void' from 'deprecate'

### ISSUE THREAD

**Issue by kavin525zhang** [facebookresearch/dpr-scale#17]
Traceback (most recent call last):
  File "/mnt/disk2/zkm/dpr-scale/dpr_scale/main.py", line 9, in <module>
    from pytorch_lightning.callbacks import LearningRateMonitor
  File "/opt/tq/miniconda3/envs/qwen/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 30, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/opt/tq/miniconda3/envs/qwen/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/opt/tq/miniconda3/envs/qwen/lib/python3.10/site-packages/pytorch_lightning/callbacks/pruning.py", line 31, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/opt/tq/miniconda3/envs/qwen/lib/python3.10/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/opt/tq/miniconda3/envs/qwen/lib/python3.10/site-packages/pytorch_lightning/core/lightning.py", line 42, in <module>
    from pytorch_lightning.trainer.connectors.data_connector import _DataHookSelector
  File "/opt/tq/miniconda3/envs/qwen/lib/python3.10/site-packages/pytorch_lightning/trainer/__init__.py", line 16, in <module>
    from pytorch_lightning.trainer.trainer import Trainer
  File "/opt/tq/miniconda3/envs/qwen/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 42, in <module>
    from pytorch_lightning.loops import PredictionLoop, TrainingEpochLoop
  File "/opt/tq/miniconda3/envs/qwen/lib/python3.10/site-packages/pytorch_lightning/loops/__init__.py", line 15, in <module>
    from pytorch_lightning.loops.base import Loop  # noqa: F401
  File "/opt/tq/miniconda3/envs/qwen/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 18, in <module>
    from deprecate import void
ImportError: cannot import name 'void' from 'deprecate' (/opt/tq/miniconda3/envs/qwen/lib/python3.10/site-packages/deprecate.py)
这个包安装了， 但里面没有void这个函数，试了各个版本都不行

**Comment by ccsasuke** [comment]
Hi @kavin525zhang, this might be caused by using a newer python version (3.10). Could you try setting up a new python 3.8 environment and reinstall the dependencies, and see if that works?
